CREATE TABLE PUBLIC.PESSOA (
	CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	LOGRADOURO VARCHAR(50),
	NUMERO VARCHAR(50),
	COMPLEMENTO VARCHAR(50),
	BAIRRO VARCHAR(50),
	CEP VARCHAR(50),
	CIDADE VARCHAR(50),
	ESTADO VARCHAR(50),
	ATIVO BOOLEAN NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO PESSOA
(CODIGO, NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, ATIVO)
VALUES(1, 'Ricardo', 'abc', '123', 'xpto', 'aaa', '11111111', 'bbb', 'ccc', true);
INSERT INTO PESSOA
(CODIGO, NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, ATIVO)
VALUES(2, 'Tayne', 'abc', '123', 'xpto', 'aaa', '11111111', 'bbb', 'ccc', true);
INSERT INTO PESSOA
(CODIGO, NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, ATIVO)
VALUES(3, 'Kalel', 'abc', '123', 'xpto', 'aaa', '11111111', 'bbb', 'ccc', true);
INSERT INTO PESSOA
(CODIGO, NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, ATIVO)
VALUES(4, 'Kyra', 'abc', '123', 'xpto', 'aaa', '11111111', 'bbb', 'ccc', true);
INSERT INTO PESSOA
(CODIGO, NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, ATIVO)
VALUES(5, 'Jhon', 'abcd', '0123', 'xptoss', 'cbaaa', '11111000', 'cccbbb', 'dddccc', false);
INSERT INTO PESSOA
(CODIGO, NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, ATIVO)
VALUES(6, 'Mary', 'abczz', '00123', 'xptozz', 'vvaaa', '00011111', 'hhbbb', 'crrc', false);
