CREATE TABLE LANCAMENTO (
	CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL,
	DATA_VENCIMENTO DATE NOT NULL,
	DATA_PAGAMENTO DATE,
	VALOR DECIMAL(10,2) NOT NULL,
	OBSERVACAO VARCHAR(100),
	TIPO VARCHAR(20) NOT NULL,
	CODIGO_CATEGORIA BIGINT NOT NULL,
	CODIGO_PESSOA BIGINT NOT NULL,
    FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES CATEGORIA(CODIGO),
    FOREIGN KEY (CODIGO_PESSOA) REFERENCES PESSOA(CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO LANCAMENTO
(CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES(1, 'Aluguel mensal', '2023-01-01', NULL, 1000.00, 'Aluguel', 'RECEITA', 2, 1);
INSERT INTO LANCAMENTO
(CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES(2, 'Transporte', '2023-02-01', NULL, 800.00, 'Gastos', 'DESPESA', 3, 2);
INSERT INTO LANCAMENTO
(CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES(3, 'Salario', '2023-06-01', NULL, 4000.00, 'Lucros', 'RECEITA', 1, 3);
INSERT INTO LANCAMENTO
(CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES(4, 'Mensalidade', '2023-04-01', NULL, 900.00, 'Distribuição de lucros', 'DESPESA', 6, 4);
INSERT INTO LANCAMENTO
(CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES(5, 'Saude', '2023-09-01', NULL, 1500.00, 'Gastos', 'RECEITA', 4, 5);
INSERT INTO LANCAMENTO
(CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES(6, 'Abono', '2023-10-01', NULL, 6000.00, 'Perda lucros', 'RECEITA', 5, 6);
